services:
  - type: web
    name: jobcrab-python-scraper
    env: docker
    plan: free
    rootDir: python-service
    envVars:
      - key: PYTHON_SERVICE_API_KEY
        generateValue: true
      - key: FIRECRAWL_API_KEY
        sync: false
