services:
  - type: web
    name: jobcrab-python-scraper
    env: python
    plan: free
    rootDir: python-service
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium chrome
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHON_SERVICE_API_KEY
        generateValue: true
      - key: FIRECRAWL_API_KEY
        sync: false
